# Stage 1: Build
FROM maven:3.8.6-openjdk-18 AS build

WORKDIR /app

# Copy only the pom.xml and download dependencies in a separate layer
COPY pom.xml .

RUN mvn dependency:go-offline

# Copy the rest of the source code
COPY src ./src

# Build the project, skipping tests to speed up the process
RUN mvn -B clean package -DskipTests


# Stage 2: Runtime
# FROM gcr.io/distroless/java17-debian11 AS runtime
FROM openjdk:17-jdk-slim AS runtime

WORKDIR /app

# Copy only the necessary JAR file from the build stage
COPY --from=build /app/target/*.jar /app/associate-service.jar

EXPOSE 9098

CMD ["java", "-jar", "associate-service.jar"]
